///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterData recording.
    /// </summary>
    [TestModule("d48deffb-f3aa-4ada-9471-8afc7cf20be5", ModuleType.Recording, 1)]
    public partial class EnterData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static EnterData instance = new EnterData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterData()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterData Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            ClickAndType("Jason", repo.ApplicationUnderTest.Web_VIP_initial_Screen.FirstName);
            Delay.Milliseconds(0);
            
            ClickAndType("Branham", repo.ApplicationUnderTest.Web_VIP_initial_Screen.LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Web_VIP_initial_Screen.Music' at 18;11.", repo.ApplicationUnderTest.Web_VIP_initial_Screen.MusicInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Web_VIP_initial_Screen.Music.Click("18;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Web_VIP_initial_Screen.Gender' at 10;7.", repo.ApplicationUnderTest.Web_VIP_initial_Screen.GenderInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Web_VIP_initial_Screen.Gender.Click("10;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Web_VIP_initial_Screen.InputTagAdd' at 22;7.", repo.ApplicationUnderTest.Web_VIP_initial_Screen.InputTagAddInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Web_VIP_initial_Screen.InputTagAdd.Click("22;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='VIP count: 1') on item 'ApplicationUnderTest.Web_VIP_initial_Screen.Count'.", repo.ApplicationUnderTest.Web_VIP_initial_Screen.CountInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.Web_VIP_initial_Screen.CountInfo, "InnerText", "VIP count: 1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Web_VIP_initial_Screen.Clear' at 32;12.", repo.ApplicationUnderTest.Web_VIP_initial_Screen.ClearInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Web_VIP_initial_Screen.Clear.Click("32;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
