///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("372436eb-abaf-417a-956b-0d8e339cb48f")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("372436eb-abaf-417a-956b-0d8e339cb48f")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "372436eb-abaf-417a-956b-0d8e339cb48f", ".\\RepositoryImages\\MyTestRepository372436eb.rximgres")
        {
            _applicationundertest = new MyTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("372436eb-abaf-417a-956b-0d8e339cb48f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("627abd26-e728-4624-98cc-7d840a0e8410")]
        public virtual MyTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("627abd26-e728-4624-98cc-7d840a0e8410")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            MyTestRepositoryFolders.Web_VIP_initial_ScreenFolder _web_vip_initial_screen;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "627abd26-e728-4624-98cc-7d840a0e8410", "")
            {
                _web_vip_initial_screen = new MyTestRepositoryFolders.Web_VIP_initial_ScreenFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("627abd26-e728-4624-98cc-7d840a0e8410")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("627abd26-e728-4624-98cc-7d840a0e8410")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Web_VIP_initial_Screen folder.
            /// </summary>
            [RepositoryFolder("1611acb6-a745-476e-a101-eab313eb45a1")]
            public virtual MyTestRepositoryFolders.Web_VIP_initial_ScreenFolder Web_VIP_initial_Screen
            {
                get { return _web_vip_initial_screen; }
            }
        }

        /// <summary>
        /// The Web_VIP_initial_ScreenFolder folder.
        /// </summary>
        [RepositoryFolder("1611acb6-a745-476e-a101-eab313eb45a1")]
        public partial class Web_VIP_initial_ScreenFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _musicInfo;
            RepoItemInfo _genderInfo;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _countInfo;
            RepoItemInfo _clearInfo;

            /// <summary>
            /// Creates a new Web_VIP_initial_Screen  folder.
            /// </summary>
            public Web_VIP_initial_ScreenFolder(RepoGenBaseFolder parentFolder) :
                    base("Web_VIP_initial_Screen", "", parentFolder, 0, null, false, "1611acb6-a745-476e-a101-eab313eb45a1", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName111']", ".//input[#'FirstName']", 30000, null, "5f666507-d8c2-4b30-a0fe-fee0e869a06b");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", ".//input[#'LastName']", 30000, null, "968282d8-aade-4c73-bcbf-677fd3d7e564");
                _musicInfo = new RepoItemInfo(this, "Music", ".//select[#'Category']/option[@value='Music']", ".//select[#'Category']/option[@value='Music']", 30000, null, "6437e500-3a4f-48bb-8220-427affa289cf");
                _genderInfo = new RepoItemInfo(this, "Gender", ".//td[#'gender']/table//input[@name='Gender' and @type='radio' and @value='male']", ".//td[#'gender']//input[@name='Gender' and @type='radio' and @value='male']", 30000, null, "56722ab2-78ed-4139-a33f-111dee336ecb");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", ".//input[#'Add']", 30000, null, "dd86e607-cad8-4268-9660-6e79341c5a3c");
                _countInfo = new RepoItemInfo(this, "Count", ".//td[#'count']", ".//td[#'count']", 30000, null, "3ea55c7c-eb24-4c37-ab4a-71ca82736372");
                _clearInfo = new RepoItemInfo(this, "Clear", ".//input[#'Clear']", ".//input[#'Clear']", 30000, null, "f452a2a5-549a-494a-aaf3-4fae4afda4e2");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1611acb6-a745-476e-a101-eab313eb45a1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("5f666507-d8c2-4b30-a0fe-fee0e869a06b")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("5f666507-d8c2-4b30-a0fe-fee0e869a06b")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("968282d8-aade-4c73-bcbf-677fd3d7e564")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("968282d8-aade-4c73-bcbf-677fd3d7e564")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("6437e500-3a4f-48bb-8220-427affa289cf")]
            public virtual Ranorex.OptionTag Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("6437e500-3a4f-48bb-8220-427affa289cf")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }

            /// <summary>
            /// The Gender item.
            /// </summary>
            [RepositoryItem("56722ab2-78ed-4139-a33f-111dee336ecb")]
            public virtual Ranorex.InputTag Gender
            {
                get
                {
                    return _genderInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Gender item info.
            /// </summary>
            [RepositoryItemInfo("56722ab2-78ed-4139-a33f-111dee336ecb")]
            public virtual RepoItemInfo GenderInfo
            {
                get
                {
                    return _genderInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("dd86e607-cad8-4268-9660-6e79341c5a3c")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("dd86e607-cad8-4268-9660-6e79341c5a3c")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Count item.
            /// </summary>
            [RepositoryItem("3ea55c7c-eb24-4c37-ab4a-71ca82736372")]
            public virtual Ranorex.TdTag Count
            {
                get
                {
                    return _countInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Count item info.
            /// </summary>
            [RepositoryItemInfo("3ea55c7c-eb24-4c37-ab4a-71ca82736372")]
            public virtual RepoItemInfo CountInfo
            {
                get
                {
                    return _countInfo;
                }
            }

            /// <summary>
            /// The Clear item.
            /// </summary>
            [RepositoryItem("f452a2a5-549a-494a-aaf3-4fae4afda4e2")]
            public virtual Ranorex.InputTag Clear
            {
                get
                {
                    return _clearInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Clear item info.
            /// </summary>
            [RepositoryItemInfo("f452a2a5-549a-494a-aaf3-4fae4afda4e2")]
            public virtual RepoItemInfo ClearInfo
            {
                get
                {
                    return _clearInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
